name: PHP report

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: report
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: php -f report.php $USERNAME $PASSWORD

